### ISSUE TITLE
Fixture load breaks

### ISSUE THREAD

**Issue by chengguangnan** [namick/obfuscate_id#14]
Saying that I have a model Product.

Then the fixture load function `products(:one)` would not load anything because the fixture ID is not generated by obfuscate_id [but some CRC32](http://stackoverflow.com/questions/3501225/how-are-ids-for-fixtures-generated).

Option `:no_obfuscated_id` doest not fix this problem as `products()`  does not directly go to the `find` method. 

My fix is disable obfuscate_id on Rails.test.

Maybe you have better ideas on this.

**Comment by PMWan** [comment]
An alternative approach to avoiding obfuscation in your test environment when using fixtures:

```
class Example < ActiveRecord::Base
  unless Rails.env.test?
    obfuscate_id spin: 43458392
  end
  ....
end
```

This worked for me.
