### ISSUE TITLE
Using find() in ApplicationController tries to find by obfuscated ID and breaks.

### ISSUE THREAD

**Issue by michaelpumo** [namick/obfuscate_id#18]
I have an ApplicationController that all controllers extend. 

In this ApplicationController, I try to do:

def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

If my user model uses the obfuscate_id, this ApplicationController throws an error on current_user:

Couldn't find User with id=5164061535

Any ideas if this is an issue / fault with the gem or am I doing this wrong?
Thanks.

**Comment by namick** [comment]
You can do this:

```
def current_user
  @current_user ||= User.find(session[:user_id], no_obfuscated_id: true) if session[:user_id]
end
```

Feel free to reopen this issue if you are still having a problem.

**Comment by mfkp** [comment]
Is `no_obfuscate_id` really a thing? I don't see it anywhere in the code

**Comment by mfkp** [comment]
Ah, it's supposed to be `no_obfuscated_id`. Nevermind.

**Comment by namick** [comment]
Oh, right.  Sorry about that.  I updated my comment.
