### ISSUE TITLE
Updating model with update_attribute doesn't work

### ISSUE THREAD

**Issue by jurezove** [namick/obfuscate_id#25]
It looks like the id doesn't get deobfuscated before performing `update_attributes`.

I'm using:

`bill = Bill.find(Bill.deobfuscate_id(params[:id]))`
`bill.update_attributes(bill_params)`

and I get

`ActiveRecord::StatementInvalid: PG::NumericValueOutOfRange: ERROR:  value "4903661204" is out of range for type integer`

**Comment by namick** [comment]
You never have to manually call `deobfuscate_id`.

Just make sure you include `obfuscate_id` in your model:
```
class Bill < ActiveRecord::Base
  obfuscate_id

  # model code
end
```

Then just do this:
```
bill = Bill.find(params[:id])
bill.update_attributes(bill_params)
```

Feel free to reopen the issue if you are still having a problem.

**Comment by jurezove** [comment]
I was encountering this when using CarrierWave and uploading attachments.

Not sure what the problem was but ended up doing a monkey patch and overriding `#has_obfuscated_id? when uploading an attachment. :)

**Comment by scottbullard** [comment]
@jurezove can you elaborate on what you did to work around your issue by using has_obfuscated_id?

I am experiencing similar problems with trying to use obfuscate_id with carrierwave.  No matter which method I use (find(obf_id) or find_by_id(orig_id)), carrierwave still has problems `with an out of range value for 'id'`

I had posted [here](https://github.com/namick/obfuscate_id/issues/36#issuecomment-100324419) a while back when at the time I believed it to be related to Resque, but it's also noted [here](https://github.com/namick/obfuscate_id/issues/2#issuecomment-13434049) quite some time ago but that fix referenced does not appear to work for this.

**Comment by jurezove** [comment]
Hey @scottbullard sorry for the late reply. In the end, I did a small hack:

```
module HackableObfuscate
  def perform_deobfuscated
    result = false
    begin
      hack_class
      result = yield
    ensure
      unhack_class
    end
    result
  end

  private

  def hack_class
    self.class_eval do
      def self.has_obfuscated_id?
        false
      end
    end
  end

  def unhack_class
    self.class_eval do
      def self.has_obfuscated_id?
        true
      end
    end
  end
end
```

Then for example, called that method:

```
Payment.perform_deobfuscated { @payment.update_attributes(payment_params) }
```

Does something like this work for you?

**Comment by scottbullard** [comment]
@jurezove thanks - I will give that a try.
