### ISSUE TITLE
Bug on batch actions with ActiveAdmin

### ISSUE THREAD

**Issue by jnettome** [namick/obfuscate_id#26]
I don't know if this can be considered bug, but when you're using obfuscate_id with active_admin, the batch actions can't find records.

Could someone help me on that? (just telling if is a bug or not... i can make a PR for that)

:+1:

**Comment by namick** [comment]
Feel free to make a PR if you can.  Even if it is just a failing test.

You can also show me a repo with active_admin that is having the problem, I could help you find it.
