### ISSUE TITLE
Speed for API

### ISSUE THREAD

**Issue by ACPK** [namick/obfuscate_id#32]
To cut down on the time for HTTPS requests, wouldn't it be better to save the random IDs in the database and index them?

**Comment by namick** [comment]
The goals of this project include not having to make extra columns in the database.

Secondly, this gem translates the obfuscated ids to normal, sequential ids before hitting the database.  These normal IDs are indexed in the database by default.

Also, this plugin will in no way affect the speed of HTTPS requests as the SSL layer decrypts the request before Rails (and this gem) ever sees it.
